name: streamlit_py312
channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - attrs==25.3.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - deprecation==2.1.0
      - et-xmlfile==2.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.16.0
      - h2==4.3.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - hyperframe==6.1.0
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - markupsafe==3.0.2
      - na
